name: goal_nepal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^2.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.2
  flutter_riverpod: ^3.1.0
  path_provider: ^2.1.5
  riverpod_annotation: ^4.0.0
  shared_preferences: ^2.5.4
  dio: ^5.4.1
  dio_smart_retry: ^7.0.1
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^7.0.0
  flutter_secure_storage: ^10.0.0
  image_picker: ^1.2.1
  flutter_launcher_icons: ^0.14.4

  #Permissions
  permission_handler: ^12.0.1
  equatable: ^2.0.5
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/luncher_icon.png
  min_sdk_android: 21
  remove_alpha_ios: true
